### ISSUE TITLE
상세페이지 전반적인 UI 개선

### ISSUE THREAD

**Issue by chuyeonbin** [wanted-pre-onboarding-fe-8/8flix#36]
## 📌개요
상세페이지 전반적인 UI 개선

- [x] 상세페이지 마크업
- [x] 상세페이지 styling
- [x] 더보기 클릭시 영화 전체내용 보여주기

## UI 개선전
<img width="620" alt="스크린샷 2022-07-12 오후 12 19 21" src="https://user-images.githubusercontent.com/40565619/178401441-64b59863-d5d9-43d9-96c2-8b70af6992a4.png">

## UI 개선후
<img width="576" alt="스크린샷 2022-07-12 오후 12 26 41" src="https://user-images.githubusercontent.com/40565619/178402382-27001167-0cbd-40c4-9eab-6b5e748b089d.png">

## 주요 수정 범위
src/components/Modal.jsx
src/pages/detail/index.jsx
src/pages/main/index.jsx
src/pages/myList/index.jsx

**Comment by corgi-world** [comment]
연빈님 지금 코드가 모달 클릭하면 닫히게 되어있어서 저 x버튼이 의미가 없을 것 같아요ㅜㅜ 우선 x버튼은 제외해주셨으면 좋겠습니다!!

**Comment by chuyeonbin** [comment]
모달 외부를 클릭해서 닫히게끔 하고 내부는 x버튼 넣어서 닫히게끔 처리하는게 좋지 않을까요?

**Comment by corgi-world** [comment]
네 그것도 좋은 방법인 것 같은데요! 그러면 detail 컴포넌트 내부로 closeModal 이라는 함수를 가져와야 됩니다!! 코드 수정이 좀 필요할 것 같아서 말씀드렸습니다!

**Comment by chuyeonbin** [comment]
성운님 방식대로하면 더보기가 작동을 안하고 모달이 닫혀버리는데 내부는 이벤트처리 안하는게 저는 좋을 것 같습니다!

**Comment by corgi-world** [comment]
그거 제가 수정하겠습니다ㅜㅜ 더보기 flag 그냥 true로 해서 열려 있는 상태로 임시 작업하는 방식으로 하시면 될 것 같아요ㅜㅠㅜ

**Comment by chuyeonbin** [comment]
성운님 번거롭게 해서 죄송합니다. 일만 키운 것 같네요 ㅠ

**Comment by corgi-world** [comment]
전~혀 아닙니다ㅋㅋㅋ 제가 그 부분 짤 때 제대로 마무리 안해서 그런거예요ㅜㅜ
